pangeo-data/xESMF

setup.py

newly implemented functionalities require esmpy>=8.0.0
this adds to the setup.py

Add ESMPy v8 to requirements, fixes #13

---

doc/conf.py
doc/index.rst
doc/installation.rst
doc/large_problems_on_HPC.rst

add HPC regridding documentation (replace PR #4)

---

CHANGES.rst

We'll probably want to fill up what happened for older versions.

Add CHANGES file

---

CHANGES.rst
doc/changes.rst
doc/conf.py
doc/index.rst
doc/requirements.txt

Copied what was on the release page. 
Note that I get a warning when compiling the docs. Any idea what might be causing this ?
```
WARNING: autodoc: failed to import module 'frontend' from module 'xesmf'; the following exception was raised:
...
File "/home/david/.conda/envs/esmf/lib/python3.8/distutils/version.py", line 335, in _cmp
if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
```

Update CHANGES.rst file with previous versions

---

README.rst
doc/requirements.txt

let's have the links pointing to the updated doc

doc links pointing to pangeo-xesmf

---

.github/workflows/ci.yaml
.gitignore
xesmf/tests/conftest.py
xesmf/tests/test_frontend.py

Test against different dask schedulers

---

setup.py

See #36
Upstream PR fixing issue: https://github.com/pydata/xarray/pull/4576

Pin xarray<=0.16.0

---

xesmf/frontend.py
xesmf/tests/test_frontend.py

Return objects consistent with ds_out coordinates

---

ci/environment-upstream-dev.yml
ci/environment.yml
setup.cfg
xesmf/tests/test_oceanmodels.py

this uses random data structured like the MOM6 ocean model to test xESMF is not breaking user cases

start adding testing for commonly used ocean models

---

xesmf/frontend.py
xesmf/tests/test_frontend.py

Fixes #72 with the help of recently-released cf_xarray 0.5. Added a test to be sure.

Fix cf bounds issue

---

CHANGES.rst
README.rst
setup.py

Patch release with a few bug fixes and documentation improvements. 
- update whats new
- update Zenodo badge
- Upgrade cf-xarray requirement to 0.5.1

Release 0.5.3 

---

doc/releases.rst

Realized one step was missing in the release docs.

Complete release docs

---

README.rst

This PR drops the pypi badge which points to the package which isn't maintained and add the conda badge which is maintained

DOC: add conda in README

---

CHANGES.rst

Please check that the description of changes is accurate. 
@stefraynaud 
@sol1105

Update CHANGES with 0.6.0 release

---

.pre-commit-config.yaml

this seems to fix the linting workflow

update blackdoc version

---

setup.py

#128 added a pin to shapely, but I was able to run all tests with the latest version. Sorry, I missed that change when reviewing.
@huard do you remember what made you pin it?

Unpin shapely

---

CHANGES.rst
setup.cfg

Prep for the 0.6.2 release.
Fix #137

polish CHANGES and add note about 0.6.1

---

.github/workflows/ci.yaml

Add a Python3.9 CI build, ensure latest branch uses Python3.9

---

doc/index.rst

Point to the generic zenodo doi for pangeo-data/xESMF instead of Jiawei's.

Update Zenodo doi

---

CHANGES.rst
doc/conf.py

Add cftime and pandas to mock imports

---

CHANGES.rst
xesmf/tests/test_util.py
xesmf/util.py

Add option to grid_global to vary longitudes from 0 to 360

---

.github/workflows/ci.yaml

ref: https://github.com/conda-incubator/setup-miniconda/issues/274
ref: https://github.com/nextstrain/cli/commit/4a764976519ca5c540c745463548a9d883eae079

implement workaround for setup conda problem

---

.github/workflows/ci.yaml

Update CI for Micromamba environments

---

.pre-commit-config.yaml

Bump isort to 5.12.0 and add default language version to  pre-commit

---

doc/installation.rst

In #240, @huard explained the installation options for ESMpy.  This PR makes it easier for others to learn those options.

Document installation options for ESMpy

---

xesmf/tests/test_frontend.py

Fix test so it works with pandas 2.0

---

.github/workflows/pypi.yaml
pyproject.toml

Follow up on https://github.com/pangeo-data/xESMF/pull/248

Minor fixes

---

CHANGES.rst

In preparation for a 0.7.1 release that would be published on PyPI.

Update CHANGES for 0.7.1

---

README.rst
doc/index.rst
doc/installation.rst
doc/other_tools.rst

Repare broken links to earthsystemcog

---

xesmf/frontend.py

This PR is related to issue #323 and fixes the bug with the para regridder

add fix for parallel regridder merge error with xarray

---

.github/workflows/ci.yaml
CHANGES.rst

A simple update of CHANGES.rst to prepare for patch release 0.8.2.

Prepare version 0.8.2

---

doc/other_tools.rst

change uvcdat link for xcdat

---

CHANGES.rst

Prepare 0.8.8

---

.github/workflows/ci.yaml

Test against python 3.13, stop testing with python 3.8, test against ESMF 8.8.

---

CHANGES.rst

Patch release for releasing #428.

Prepare v0.8.10
