pangeo-data/xESMF

CHANGES.rst, xesmf/frontend.py
This fixes JiaweiZhuang/xESMF#71 and #38.
There are currently no tests in the test suite that use distributed dask client, so all I can say is that solved the problem on my machine with dask 2.17. 
From what I understand the problem of using a distributed client is that it must serialize everything it sends to its workers. In the `Regridder` object, we keep the ESMpy Grid/Mesh/Locstream objects, which are not serializable by dask. Thus the error and the workaround that dumped overwrote `_grid_in` and `_grid_out` to `None` (see  JiaweiZhuang/xESMF#71).  I figured out that those two objects were passed to dask only because we were wrapping `Regridder.regrid_numpy` which is a _bound_ method, meaning the whole `Regridder` instance has to passed together with the function to the workers.
This …
=> Use unbound regridding method for dask wrapping

xesmf/__init__.py
Fixes https://github.com/pangeo-data/xESMF/issues/32
Currently, we are using [setuptools-scm](https://github.com/pypa/setuptools_scm/) for managing the package version:
https://github.com/pangeo-data/xESMF/blob/80fdfd40edf9255b6639f82b9ac9dd03318e4919/setup.py#L11-L12
However, the version information was being hard-coded in `__init__.py`. This PR removes the hard-coded version information, and dynamically retrieves the package version via `pkg_resources`. 
P.S.: With `setuptools-scm`, the version information is retrieved from the git tags/commits. So, when it comes to releases, we don't need to bump `__version__` in the package. The only requirement is to publish a release on GitHub and the version information will be propagated by `setuptools-scm`.
=> Retrieve package version at runtime

CHANGES.rst, doc/installation.rst
=> Update installation docs to mention that PyPi only holds xesmf up to version 0.3.0

doc/conf.py, doc/requirements.txt
I've noticed that the documentation was not building correctly the Regridder API: https://pangeo-xesmf.readthedocs.io/en/latest/user_api.html#regridder
This should fix it (it's working on my local machine).
=> fix API in documentation

MANIFEST.in
The GitHub Action that creates the tarball was failing b/c these files failed the MANIFEST check. This is not too important but it is nice to get this test fixed b/c when we add a file that we do want in the tarball we can catch the failure and fix it early.
=> Fix tarball check

ci/environment-upstream-dev.yml, ci/environment.yml, setup.cfg, xesmf/frontend.py, xesmf/tests/conftest.py, xesmf/tests/test_oceanmodels.py
Well this is embarrassing and quite urgent. Looks like PR #49 broke my regridding of MOM6 data.
The default behavior is now a breaking change and I did not catch it in my review. I strongly think
that the default behavior should mimic the old behavior (i.e. looking for `lon` and `lat` in dataset).
This PR reintroduce the old behavior and only switch to using cf-xaray if `lon` and `lat` are not present.
I also added a realistic test case using MOM6 ocean data pulled from opendap to avoid another bad surprise
in the future.
@huard @aulemahal I'd like us to move quickly on this and we probably need to push another release soon too!
=> bug fix read lon/lat

xesmf/frontend.py, xesmf/tests/test_frontend.py
This PR fixes #53.
Changes `ds_to_ESMFgrid` and `ds_to_ESMFlocstream` so that they also return the dimension names (in the correct order), or None if the input was not a xarray object. These names are then saved in the Regridder object (new arg for BaseRegridder) as `self.in_horiz_dims`.
Upon regridding a DataArray or a Dataset, `parse_xrinput` checks if `self.in_horiz_dims` is not None and that all the dims listed there are present in the xr object, in which case those are passed to the `apply_ufunc` call, letting xarray align the dimensions. Otherwise, it defaults back to the old behavior : taking the last dimensions of the first data variable. 
Thus, this allows regridding a dataset or dataarray where the (first) variable doesn't have the same dimension order than the object used for …
=> Regrid xarray by matching dimension names

xesmf/frontend.py, xesmf/tests/test_frontend.py
The fix in #64 for extracting lat/lon from non-cf-compliant fields didn't work if the input was a DataArray. This is a simple change to check for lat/lon with the `.coords` method, which works for either DataArrays or Datasets.
=> Fix lon/lat extraction for DataArrays

xesmf/frontend.py, xesmf/tests/test_frontend.py
When regridding datasets directly, any data variable that doesn't have the regridded dimensions will make the `apply_ufunc` call fail. In my experience, I often find things like "time_bnds" or "rotated_pole" as data variables. 
The workarounds are easy : either drop the culprits, set them as coords or regrid the dataarrays in a loop.
However, it might be interesting to solve this directly in xESMF? Simply yet-another-workaround avoided for the end user. I suggest this easy solution where variables not containing the regridded dimensions are simply skipped.
=> Allow non-regriddable vars in datasets

xesmf/frontend.py, xesmf/tests/test_frontend.py
`locations` is currently the hard-coded dimension name given to outputs when using `locstream_out=True`.
This PR uses the same name as `ds_out` when the coordinates have consistent dimension names.
=> locstream dim name consistent with ds_out

xesmf/frontend.py, xesmf/tests/test_frontend.py
As explained in #29, the regridding leads to unexpected results when the input dataset has transient values i.e. when the number of missing values varies along dimensions other than the horizontal ones.
This PR fixes #29 by normalising the results with the regridded transient mask.
=> Add basic adaptive masking to solve #29

xesmf/frontend.py, xesmf/tests/test_frontend.py
BaseRegridder: Applying weight modification add_nans_to_weights as default for all but nearest neighbour regridding methods. Fixes #56 
- Instead of being applied only in presence of an output mask, `add_nans_to_weights` will now be applied by default
during the BaseRegridder initialization for all but the nearest neighbour regridding methods (nearest_s2d,
nearest_d2s).
- The default parameter "apply_add_nans_to_weights = True" has been added to `BaseRegridder.__init__()`,
causing above behaviour.
- The `SpatialAverager` class has been modified to include the parameter `apply_add_nans_to_weights = False`
when initializing BaseRegridder / Regridder to preserve its original behaviour.
- Added in tests/test_frontend: `test_to_netcdf_nans`
- Modified in tests/test_frontend: `test_to_netcdf`, …
=> Set add_nans_to_weights as default as discussed in #56

setup.py, xesmf/frontend.py
Since https://github.com/pydata/xarray/pull/4060, xesmf has given a FutureWarning for supplying `output_sizes` directly in `xr.apply_ufunc` rather than through `dask_gufunc_kwargs`.
```python
import xarray as xr
import xesmf as xe
ds = xr.tutorial.open_dataset('air_temperature')
regridder = xe.Regridder(ds, ds[['lon', 'lat']], 'bilinear')
regridder(ds)
```
```
xesmf/frontend.py:555: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
ds_out = xr.apply_ufunc(
```
This eliminates the warning.
=> FutureWarning in apply_ufunc

CHANGES.rst, ci/environment.yml, doc/conf.py, doc/requirements.txt, readthedocs.yml, setup.py, xesmf/backend.py, xesmf/data.py, xesmf/frontend.py, xesmf/smm.py, xesmf/tests/test_frontend.py, xesmf/util.py
Fix #126
The original implementation used to compute the grid weights over
ds_in : polygon mesh
ds_out : source grid
and then rename out_dim and in_dim to in_dim and out_dim. This simplified the code's logic but had the effect of neglecting variations in source grid cell areas. 
The fix sets source and destination to their expected order, but needs to grab the destination field area from the regrid object to perform a necessary renormalization between exteriors and interiors. This required a bit of refactoring which hopefully will clarify what's going on. 
A test was added to make sure weights computed using an output mesh and an output grid are nearly identical.
=> Fix SpatialAverager to account for variable input grid cells areas

CHANGES.rst, setup.cfg, xesmf/smm.py, xesmf/tests/test_frontend.py
Fixes #124.
#111 introduced an unforeseen constrain : machine architectures and data dtypes are now restricted by what `numba` supports. `numba` is used by `sparse` under the hood. I have not heard of problems with machine architectures, but issue #124 is due to data coming from a different computer that uses "big-endian" (numpy's ">f8" dtype).
~This introduces on-the-fly byte-swapping, to convert to little-endian. The performance cost is unmeasured, but should be quite low. I find it a bit ugly to perform that conversion in xESMF instead of `sparse` directly, but this is the fastest solution I could think of.~
EDIT: Instead of converting dtypes on-the-fly, I converted the weights from it's `sparse` format to a `scipy` matrix, which doesn't use numba and thus resolves the problem. It also …
=> On-the-fly endianness conversion

CHANGES.rst, setup.cfg, xesmf/frontend.py, xesmf/smm.py, xesmf/tests/test_frontend.py
This fixes #127 and fixes #117 (maybe that one was already fixed?).
At the beginning, I tried to explore @dcherian's idea of using dask's `tensordot` directly instead of wrapping everything in a  `xr.apply_ufunc` with `dask='parallelized'`. Sadly, that didn't go as well as planned : the performance was not better, sometimes it was equal, sometimes worst. But, building on that, I moved things around to see if it could improve.  I'm a bit disappointed as this final solution is not _that_ much more performant than before...
The dask graph issue (127) is fixed explicitly by wrapping the weights into a dask array ourselves. I could have done just that, but the changes here have the following bonuses:
- Reorder the checks and the computation : shape checks are now done _before_ the computation, …
=> Reduce dask task count, refactor regrid dispatch

.pre-commit-config.yaml, ci/environment-upstream-dev.yml, ci/environment.yml, setup.py, xesmf/tests/test_frontend.py
Fixes #158 
I tried sparse 0.7.0, 0.8.0, 0.9.1 and 0.10.0 (current is 0.13.0) and only 0.7.0 made the test suite fail. I thus assumed the minimum version to be 0.8.0.
Our explicit use of `numba` is very superficial, I didn't really check what the minimum version would be. We could simplify the code by pinning 0.55, but that's the last minor version, it felt too soon to pin only to remove half a line.
I also updated the pre-commit hooks (there was a bug with my version of black).
=> Fix dependencies - sparse and numba

CHANGES.rst, xesmf/tests/test_util.py, xesmf/util.py
=> Modify the `stop` argument in arange to avoid coordinates going over the right bound

CHANGES.rst, ci/environment.yml, setup.cfg, setup.py, xesmf/backend.py, xesmf/tests/test_backend.py, xesmf/tests/test_frontend.py
fall back on old name if the import fails
=> try importing esmpy (aliased to ESMF) for esmpy >= 8.4.0 fixes #212

CHANGES.rst, ci/environment.yml, setup.py, xesmf/backend.py
This PR modifies this single line of code that was making xESMF fail with shapely 2.0. The fix works with shapely 1.8. I'm not sure why I wrote it the way it was written, but everything passes now, so...
=> Unpin and fix for Shapely 2.0

README.rst
There is a change mentionned at https://github.com/badges/shields/issues/8671 which needs to be applied for the shields badges to work again
=> Fix ci/cd badge for build status

.github/workflows/ci.yaml
Changed .github/workflows/ci.yaml to include python 3.11 since numba 0.57.0 is now compatible with python 3.11
=> Perform ci tests with python 3.11 now that numba is compatible.

.github/workflows/ci.yaml, CHANGES.rst, doc/installation.rst, doc/requirements.txt, pyproject.toml, readthedocs.yml
RtD problem was caused by a new Sphinx version (7.0), which is not yet supported by sphinx_rtd_theme.
=> Removed 3.7 from supported versions. Build docs using 3.9

CHANGES.rst, xesmf/frontend.py, xesmf/tests/test_frontend.py
Fixes #275
- Add `w` property
- Add test
- Also added a mark.fail test showing how averages on large regions can fail. Intended for later work.
=> Added `w` property to Regridder and SpatialAverager

CHANGES.rst, xesmf/frontend.py, xesmf/tests/test_frontend.py
The `SpatialAverager.w`  property outputs an intuitive 3D weights array. However, the mechanism to guess output chunks (when None is passed, the default) is in the `BaseRegridder` and it assumed that  `w` was 4D.
This PR changes how we guess those output chunks:
- Default chunks at most as large as the out shape.
- Don't use `self.w` internally. I take the stance that `self.w` is for the user, meaning we can make it as intuitive as possible. The regridder mechanism makes the non-intuiive choice of using an out shape of (1, N) for the SpatialAverager, so I use the `self.weights` array directly instead. Also, we didn't need the DataArray container, so it removed (minimal) overhead.
- Accept len-1 `output_chunks` when it's a `sequence_out`, but add the dummy singleton dimension before …
=> Correctly guess output chunks for SpatialAverager

CHANGES.rst, xesmf/frontend.py
Fixes #338 
We were using a method from `xr.core.pycompat` that was removed. That module is private, so this was a mistake on our end.
Also, the method was only used to check if a dataArray was dask-backed and load it if it was. However, calling `load()` on any array has the exact same effect anyway.
Seeing how this impacted downstream packages, this might warrant a minor or patch release!
=> Remove function from private xarray module

CHANGES.rst
Woopsi.
`CHANGES.rst` hadn't been updated for version 0.8.2, so I was mistaken with the next release's version number.
We actually need to release 0.8.3 which only contains the bug fix for xarray 2024.02.0.
=> Prepare v0.8.3

CHANGES.rst, xesmf/frontend.py, xesmf/tests/test_frontend.py
Another patch release for a quick fix.
Fixes #343 by skipping the rename if the coordinate has the same name as a dimension, in which cas renaming has already been done. I also added a test of the parallel regridder for that case.
We didn't catch that because our test dataset is "curvilinear", i.e. the dimensions are different from the coords (which are 2D). The bug was affecting rectilinear datasets (coords == dims, both 1D).
Finally, I removed a duplicated in the CHANGES.
=> Fix parallel regridder regression and version 0.8.4

CHANGES.rst
This PR simply updates the `changes` file in preparation for a v0.8.5 release of xESMF in order for the chunking behaviour update to be available to users.
=> Prepare v0.8.5

CHANGES.rst, xesmf/smm.py
=> Compatibility with Numpy 2.0

CHANGES.rst
Update the changes file for a 0.8.6 version containing nunpy 2.0 compatibility and the `cell_area` utility.
=> Bug fix version 0.8.6

CHANGES.rst, xesmf/backend.py
Fixes #315
ESMpy has stored its grid sizes in `int32` forever, but before numpy 2 our  `get_shape` function was returning normal ints while it now returns `np.int32` scalars with numpy 2.0.
The reason is that `tuple(np.array([1, 1], dtype=np.int32))` changed behaviour in numpy 2, preserving the dtype of the individual elements in the tuple, while it previously implicitly casted them with python's scalar. See https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion
=> Another numpy 2 fix

.github/workflows/ci.yaml, CHANGES.rst, xesmf/frontend.py
We overlooked a deprecation warning that was there for the last year, and now the recent xarray breaks the parallel weight generation...
This fixes the issue.
It also enables a CI run with ESMF 8.7 which was released 3 weeks ago.
=> Fix deprecation error in xarray 2024.10

CHANGES.rst, xesmf/frontend.py
While doing the other PR I stumbled upon an issue with sparse 0.16, which is not yet released. In the  `SpatialAverager`, when the polygon has holes, we compute the weights of the holes and then invert them. The inversion of a  `COO` array also inverts its `fill_value`. Weights are float, so a fill value of `0.0` gets reverted to `-0.0`. It seems that up to sparse 0.15.4, this was not a problem but with 0.16, the subsequent concatenation of the weights fails. I was told that this was not a bug : https://github.com/pydata/sparse/issues/802
So here is a fix for that.
Also, I modified the `__del__` methods. When the `__init__` of either `Regridder` or `SpatialAverager` fails before reaching the `super().__init__`, `self.grid_in` doesn't exist yet. The `AttributeError` raised when deleting …
=> Fix upcoming sparse change

readthedocs.yml
Hopefully this fixes the RtD build. 
Note that I set `fail_on_warning` to false. Ideally we'd set it to true, but I don't have time right now to fix deeper issues.
=> Add sphinx config to readthedocs.yaml

CHANGES.rst, xesmf/backend.py, xesmf/frontend.py
Cleanest solution to #401 I could think of. An alternative less breaking solution would be to simply revert #387.
Once the weights are generated, we do not need the ESMpy grids (or locstreams) anymore. In fact, before #24, the grid were "destroyed" (they memory explicitly released by ESMpy) once the regrid was done. That meant that `Regridder.grid_in` was still there and with  most properties accessible, but most methods would fail, with a segmentation fault. When implementing the Spatial Averager, I needed to reuse grid objects for multiple ESMpy regrid calls, so I commented out the explicit `destroy`. 
As shown in JiaweiZhuang/xESMF#53, this creates a memory leak. #387 added these `destroy` back, as suggested by a comment on that thread. However, the moment they are executed  seems to …
=> Do not store grids, destroy them after usage

.pre-commit-config.yaml, CHANGES.rst, pyproject.toml, setup.cfg, xesmf/frontend.py, xesmf/tests/test_frontend.py
As title says.
Fixes #417.
As a way to make this easier, I changed the type of `Regridder.out_coords` from a dictionary to a dataset.
=> Do not add scalar coords from the target grid to the regridding output

CHANGES.rst
A small release so we have a published version with the improvements to the grid destroying.
=> Prepare v0.8.9

CHANGES.rst, xesmf/frontend.py, xesmf/tests/conftest.py, xesmf/tests/test_frontend.py, xesmf/tests/test_oceanmodels.py
Fixes #428.
Also detects or filters almost all warnings, so that we can use pytest's warning detection in a meaningful way.
=> Fix passing grid as dictionary
